package Frame;

import Model.DAO;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Frank
 */
public class ReportFilter extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ReportFilter() {
        initComponents();
        setDatePicker();
        setSteps();
        
        
    }
    
    private void setDatePicker() {
        Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.YEAR, -2);
        txtStartDate.setMinSelectableDate(calendar.getTime());

        calendar = Calendar.getInstance();
        calendar.add(Calendar.DATE, -1);
        txtStartDate.setMaxSelectableDate(calendar.getTime());

        calendar = Calendar.getInstance();
        calendar.add(Calendar.YEAR, -2);
        txtEndDate.setMinSelectableDate(calendar.getTime());

        calendar = Calendar.getInstance();
        calendar.add(Calendar.DATE, -1);
        txtEndDate.setMaxSelectableDate(calendar.getTime());
    }

    private void setSteps() {
        txtStepId.removeAllItems();
        DAO dao = new DAO();
        List<String> steps = dao.getStepID();
        txtStepId.addItem("All");
        for (String step : steps ) {
            txtStepId.addItem(step);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtStartDate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtEndDate = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtStepId = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtTimePeriod = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtEmpName = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(1, 4));

        jLabel1.setText("Date Range");
        jPanel1.add(jLabel1);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        txtStartDate.setDateFormatString("yyyy-MM-dd");
        txtStartDate.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtStartDateAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtStartDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtStartDatePropertyChange(evt);
            }
        });
        jPanel3.add(txtStartDate);

        jPanel1.add(jPanel3);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("To:");
        jPanel1.add(jLabel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        txtEndDate.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(txtEndDate);

        jPanel1.add(jPanel4);

        jPanel2.setLayout(new java.awt.GridLayout(3, 2, 0, 20));

        jLabel5.setText("Step ID");
        jPanel2.add(jLabel5);

        txtStepId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));
        jPanel2.add(txtStepId);

        jLabel6.setText("Time Period");
        jPanel2.add(jLabel6);

        txtTimePeriod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hourly (Default)", "Daily", "Weekly", "Monthly", "Yearly" }));
        txtTimePeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimePeriodActionPerformed(evt);
            }
        });
        jPanel2.add(txtTimePeriod);

        jLabel7.setText("Employee Name");
        jPanel2.add(jLabel7);

        txtEmpName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(txtEmpName);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel6.add(btnCancel);

        btnGenerate.setText("Generate Report");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });
        jPanel6.add(btnGenerate);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        String sDate = ((JTextField) txtStartDate.getDateEditor().getUiComponent()).getText();
        String eDate = ((JTextField) txtEndDate.getDateEditor().getUiComponent()).getText();
        String stepId = txtStepId.getSelectedItem().toString();
        String aggTime = txtTimePeriod.getSelectedItem().toString();
        String empName = txtEmpName.getSelectedItem().toString();
        if ((sDate != null && !sDate.equals("")) && (eDate != null && !eDate.equals(""))
                && !empName.equals("")) {
            this.dispose();
            new Report().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(new JPanel(), "Select all fields!", "", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtTimePeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimePeriodActionPerformed
        System.out.println("hi");
    }//GEN-LAST:event_txtTimePeriodActionPerformed

    private void txtStartDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtStartDatePropertyChange
        System.out.println("step");
    }//GEN-LAST:event_txtStartDatePropertyChange

    private void txtStartDateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtStartDateAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartDateAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportFilter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JComboBox<String> txtEmpName;
    private com.toedter.calendar.JDateChooser txtEndDate;
    private com.toedter.calendar.JDateChooser txtStartDate;
    private javax.swing.JComboBox<String> txtStepId;
    private javax.swing.JComboBox<String> txtTimePeriod;
    // End of variables declaration//GEN-END:variables
}
